// Configuration for YTPlayer
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25000;
var channelName = "yevheniikoral";
var auth="dqDSrVv4lY1kZTy6hS8N72LfBlc2tF";
var http="https://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
