# Используем официальный образ Node.js
FROM node:20-slim

# Рабочая директория в контейнере
WORKDIR /app

# Копируем только package-файлы, устанавливаем зависимости
COPY package*.json ./
RUN npm ci --only=production

# Копируем остальной код
COPY . .

# Прописываем порт (если нужно, например 3000)
EXPOSE 3000

# Определяем команду запуска
CMD ["node", "launch.js"]
